// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rinuzcomcezxfzdotiwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpbnV6Y29tY2V6eGZ6ZG90aXd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NjYwMzAsImV4cCI6MjA3MjE0MjAzMH0.d4BOGcx0zQUienNeFAHNtybmh20U3wDESbGsO-rNYxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});